# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20161112_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_c',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment_l',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='cource',
            old_name='descrbtion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cource',
            old_name='pupdate',
            new_name='pup_date',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='pupdate',
            new_name='pup_date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
